services:
  mkdocs:
    build: .
    image: my-developer-portal
    ports:
      - "8000:8000"
    volumes:
      - ./:/docs
    # O Entrypoint já é "mkdocs", então removemos a palavra "mkdocs" do comando
    command: serve --dev-addr=0.0.0.0:8000
